export const Query_Keys = {
  getUser: "user",
  profile: "profile",
  address: "address",
  order: "order",
  orders: "orders",
  product: "product",
  brand: "brand",
  product_comment: "product_comment",
  main_category: "main_category",
  category: "category",
  getProducts: "products",
  getProductComments: "product_comments",
  getMainCategories: "main_categories",
  getCategories: "categories",
  getBrands: "brands",
  getSpecs: "specs",
  getSelectedProducts: "selected_products",
  getCurrencyRates: "currency_rates",
  searchProducts: "searched_products",
  wishlist: "wishlist",
  product_images: "product_images",
  order_items: "order_items",
};

export const Query_Tables = {
  addresses: "addresses",
  brands: "brands",
  categories: "categories",
  main_categories: "main_categories",
  order_items: "order_items",
  orders: "orders",
  product_comments: "product_comments",
  product_faqs: "product_faqs",
  product_images: "product_images",
  product_specs: "product_specs",
  products: "products",
  profiles: "profiles",
  spec_values: "spec_values",
  specs: "specs",
  wishlists: "wishlists",
};
