export const Query_Keys = {
  getUser: "user",
  profile: "profile",
  address: "address",
  order: "order",
  orders: "orders",
  product: "product",
  brand: "brand",
  product_comment: "product-comment",
  main_category: "main-category",
  category: "category",
  getProducts: "products",
  getProductComments: "product-comments",
  getMainCategories: "main-categories",
  getCategories: "categories",
  getBrands: "brands",
  getSpecs: "specs",
  getSelectedProducts: "selected-products",
  getCurrencyRates: "currency-rates",
  searchProducts: "searched-Products",
  wishlist: "wishlist",
  product_images: "product-images",
};

export const Query_Tables = {
  addresses: "addresses",
  brands: "brands",
  categories: "categories",
  main_categories: "main_categories",
  order_items: "order_items",
  orders: "orders",
  product_comments: "product_comments",
  product_faqs: "product_faqs",
  product_images: "product_images",
  product_specs: "product_specs",
  products: "products",
  profiles: "profiles",
  spec_values: "spec_values",
  specs: "specs",
  wishlists: "wishlists",
};
