import type { ICustomer } from "../types/Customer";

export const dummyCustomers: ICustomer[] = [
  {
    id: "1",
    name: "Alice Johnson",
    location: "New York, USA",
    avatar: "/avatars/alice.png",
    comment: "Absolutely love this product! Highly recommended.",
    rating: 5,
    verified: true,
    createdAt: "2026-03-01T10:30:00Z",
  },
  {
    id: "2",
    name: "Bob Smith",
    location: "Los Angeles, USA",
    avatar: "/avatars/bob.png",
    comment: "Good quality, but a bit pricey for my taste.",
    rating: 4,
    verified: true,
    createdAt: "2026-02-28T14:15:00Z",
  },
  {
    id: "3",
    name: "Catherine Lee",
    location: "London, UK",
    avatar: "/avatars/catherine.png",
    comment: "Arrived on time and works perfectly. Great service!",
    rating: 5,
    verified: false,
    createdAt: "2026-03-02T08:45:00Z",
  },
  {
    id: "4",
    name: "David Kim",
    location: "Seoul, South Korea",
    avatar: "/avatars/david.png",
    comment: "The build quality is excellent. Highly satisfied.",
    rating: 5,
    verified: true,
    createdAt: "2026-03-03T12:00:00Z",
  },
  {
    id: "5",
    name: "Elena Garcia",
    location: "Madrid, Spain",
    avatar: "/avatars/elena.png",
    comment: "Pretty good, but I expected better packaging.",
    rating: 4,
    verified: false,
    createdAt: "2026-03-01T16:20:00Z",
  },
  {
    id: "6",
    name: "Frank Müller",
    location: "Berlin, Germany",
    avatar: "/avatars/frank.png",
    comment: "Works as described. No complaints so far.",
    rating: 4,
    verified: true,
    createdAt: "2026-02-27T09:10:00Z",
  },
  {
    id: "7",
    name: "Grace Liu",
    location: "Shanghai, China",
    avatar: "/avatars/grace.png",
    comment: "Amazing product, definitely worth the price.",
    rating: 5,
    verified: true,
    createdAt: "2026-03-04T11:50:00Z",
  },
  {
    id: "8",
    name: "Hiro Tanaka",
    location: "Tokyo, Japan",
    avatar: "/avatars/hiro.png",
    comment: "Good value for money, arrived on time.",
    rating: 4,
    verified: false,
    createdAt: "2026-03-03T15:30:00Z",
  },
  {
    id: "9",
    name: "Isabella Rossi",
    location: "Rome, Italy",
    avatar: "/avatars/isabella.png",
    comment: "Beautiful design and excellent performance.",
    rating: 5,
    verified: true,
    createdAt: "2026-03-02T18:05:00Z",
  },
  {
    id: "10",
    name: "Jack Wilson",
    location: "Toronto, Canada",
    avatar: "/avatars/jack.png",
    comment: "Good overall, but shipping took longer than expected.",
    rating: 4,
    verified: false,
    createdAt: "2026-03-01T20:15:00Z",
  },
];
