import type { IProduct } from "../types/Product";

export const dummyProducts: IProduct[] = [
  {
    id: "1",
    name: "Apple MacBook Pro 14",
    description: "Powerful laptop with M3 chip for professional workloads.",
    brand: "Apple",
    category: "Laptops",
    price: 2199,
    currency: "USD",
    discountPercentage: 15,
    rating: 4.8,
    stock: 12,
    images: ["/products/macbook-1.png", "/products/macbook-2.png"],
    thumbnail: "/products/macbook-thumb.png",
    specs: {
      processor: "Apple M3",
      ram: "16GB",
      storage: "512GB SSD",
      display: "14 inch Retina",
    },
    createdAt: "2026-01-01",
    updatedAt: "2026-01-01",
  },
  {
    id: "2",
    name: "Samsung Galaxy S24",
    description: "Flagship smartphone with powerful camera and AMOLED display.",
    brand: "Samsung",
    category: "Phones",
    price: 999,
    currency: "USD",
    discountPercentage: 15,
    rating: 4.7,
    stock: 25,
    images: ["/products/s24-1.png"],
    thumbnail: "/products/s24-thumb.png",
    specs: {
      display: "6.2 inch AMOLED",
      storage: "256GB",
      camera: "50MP",
      battery: "4000mAh",
    },
    createdAt: "2026-01-02",
    updatedAt: "2026-01-02",
  },
  {
    id: "3",
    name: "Sony WH-1000XM5",
    description: "Industry leading noise cancelling wireless headphones.",
    brand: "Sony",
    category: "Headphones",
    price: 399,
    currency: "USD",
    discountPercentage: 20,
    rating: 4.9,
    stock: 30,
    images: ["/products/sony-headphones.png"],
    thumbnail: "/products/sony-headphones.png",
    specs: {
      type: "Over-ear",
      battery: "30 hours",
      noiseCancelling: "Yes",
    },
    createdAt: "2026-01-03",
    updatedAt: "2026-01-03",
  },
  {
    id: "4",
    name: "Apple iPad Air",
    description: "Lightweight tablet perfect for productivity and creativity.",
    brand: "Apple",
    category: "Tablets",
    price: 699,
    currency: "USD",
    rating: 4.6,
    stock: 20,
    images: ["/products/ipad-air.png"],
    thumbnail: "/products/ipad-air.png",
    specs: {
      chip: "Apple M2",
      storage: "128GB",
      display: "10.9 inch Liquid Retina",
    },
    createdAt: "2026-01-04",
    updatedAt: "2026-01-04",
  },
  {
    id: "5",
    name: "Logitech MX Master 3S",
    description: "Premium productivity wireless mouse.",
    brand: "Logitech",
    category: "Accessories",
    price: 99,
    currency: "USD",
    discountPercentage: 18,
    rating: 4.8,
    stock: 50,
    images: ["/products/mx-master.png"],
    thumbnail: "/products/mx-master.png",
    specs: {
      connectivity: "Bluetooth",
      battery: "70 days",
    },
    createdAt: "2026-01-05",
    updatedAt: "2026-01-05",
  },
  {
    id: "6",
    name: "Dell XPS 13",
    description: "Compact ultrabook with premium build and performance.",
    brand: "Dell",
    category: "Laptops",
    price: 1499,
    currency: "USD",
    discountPercentage: 8,
    rating: 4.7,
    stock: 18,
    images: ["/products/xps13.png"],
    thumbnail: "/products/xps13.png",
    specs: {
      processor: "Intel i7",
      ram: "16GB",
      storage: "512GB SSD",
    },
    createdAt: "2026-01-06",
    updatedAt: "2026-01-06",
  },
  {
    id: "7",
    name: "PlayStation 5",
    description: "Next generation gaming console with ultra fast SSD.",
    brand: "Sony",
    category: "Gaming",
    price: 499,
    currency: "USD",
    discountPercentage: 5,
    rating: 4.9,
    stock: 10,
    images: ["/products/ps5.png"],
    thumbnail: "/products/ps5.png",
    specs: {
      storage: "825GB SSD",
      resolution: "4K",
    },
    createdAt: "2026-01-07",
    updatedAt: "2026-01-07",
  },
  {
    id: "8",
    name: "Canon EOS R6",
    description: "Professional mirrorless camera with powerful autofocus.",
    brand: "Canon",
    category: "Cameras",
    price: 2499,
    currency: "USD",
    discountPercentage: 14,
    rating: 4.8,
    stock: 8,
    images: ["/products/canon-r6.png"],
    thumbnail: "/products/canon-r6.png",
    specs: {
      sensor: "20MP Full Frame",
      video: "4K 60fps",
    },
    createdAt: "2026-01-08",
    updatedAt: "2026-01-08",
  },
  {
    id: "9",
    name: "Apple Watch Series 9",
    description:
      "Advanced smartwatch with fitness tracking and health features.",
    brand: "Apple",
    category: "Wearables",
    price: 429,
    currency: "USD",
    discountPercentage: 10,
    rating: 4.7,
    stock: 22,
    images: ["/products/apple-watch.png"],
    thumbnail: "/products/apple-watch.png",
    specs: {
      display: "Always-on Retina",
      battery: "18 hours",
    },
    createdAt: "2026-01-09",
    updatedAt: "2026-01-09",
  },
  {
    id: "10",
    name: "Razer BlackWidow V4",
    description: "Mechanical gaming keyboard with RGB lighting.",
    brand: "Razer",
    category: "Gaming",
    price: 179,
    currency: "USD",
    discountPercentage: 25,
    rating: 4.6,
    stock: 35,
    images: ["/products/razer-keyboard.png"],
    thumbnail: "/products/razer-keyboard.png",
    specs: {
      switch: "Mechanical",
      lighting: "RGB",
    },
    createdAt: "2026-01-10",
    updatedAt: "2026-01-10",
  },
];
